In [4]:
l = range(1000000)

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
d = np.arange(1000000)

In [5]:
%time for i in range(1,10): r = [x*2 for x in l]

Wall time: 4.71 s


In [6]:
%time for i in range(1,10): r = d * 2

Wall time: 339 ms


In [9]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
y = np.ones((4,4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
z = np.empty((4,4))
z
z.shape

(4, 4)

In [13]:
l = [1,2,3,4,5,6,7,8,9]
np.array(l)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a = np.arange(1,100,2)
a
a.shape
a.dtype

dtype('int32')

In [38]:
z = np.ones((10,10))
print(z)
b = z.reshape((2,2,5,5))
print(b)
b.dtype

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


dtype('float64')

In [39]:
b.ndim

4

In [40]:
z.ndim

2

In [54]:
a = np.random.randn((10))
print(a)
a.ndim

[ 0.11623053  1.29651879  0.72424279 -0.84642523 -2.3004109  -1.75530318
  1.75084148  1.20712481  0.65768474 -1.69746156]


1

In [49]:
b = np.random.randn((10))
print(b)
b.ndim

[ 0.36966633  0.22110053  1.31509153 -0.43444909  0.63856033  0.44299279
 -0.58639261  0.80636445  0.21302746 -1.15539757]


1

In [56]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 0.48589686  1.51761932  2.03933432 -1.28087432 -1.66185057 -1.31231039
  1.16444887  2.01348925  0.8707122  -2.85285913]
[-0.25343581  1.07541826 -0.59084874 -0.41197614 -2.93897123 -2.19829597
  2.33723409  0.40076036  0.44465728 -0.54206399]
[ 0.04296651  0.28666099  0.95244556  0.36772867 -1.46895113 -0.77758665
 -1.02668051  0.97338253  0.14010491  1.96124296]
[ 0.3144201   5.86393342  0.55071664  1.94827256 -3.60249581 -3.96237415
 -2.98578365  1.49699657  3.0873238   1.46915798]
[ 0.73933267  0.44220106  2.63018306 -0.86889817  1.27712065  0.88598558
 -1.17278523  1.61272889  0.42605492 -2.31079513]


In [61]:
b+1

array([ 1.36966633,  1.22110053,  2.31509153,  0.56555091,  1.63856033,
        1.44299279,  0.41360739,  1.80636445,  1.21302746, -0.15539757])

In [62]:
b>1

array([False, False,  True, False, False, False, False, False, False,
       False])

In [64]:
b[b>1] # to get the element greater than 1

array([1.31509153])

# indexing and slicing

In [70]:
x = np.array([1,2,3,4,5,6,7,8,9,0])
print(x)
x

[1 2 3 4 5 6 7 8 9 0]


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [73]:
x.ndim
x.dtype
x.shape

(10,)

In [96]:
x[1]
x[[5,9]]

array([6, 0])

In [76]:
x[x>5]

array([6, 7, 8, 9])

In [77]:
x[x<5]

array([1, 2, 3, 4, 0])

In [78]:
x<6

array([ True,  True,  True,  True,  True, False, False, False, False,
        True])

In [95]:
print(x)
x[2:5]
x[:5]
x[2:]
x[-6:-1]
x[-5:]
x[0:-3]
x[-3:0]# will return empty array([], dtype=int32)


[1 2 3 4 5 6 7 8 9 0]


array([], dtype=int32)

In [117]:
np.random.randn(2,2,2,5,3)#(dim,dim,dim,row,column)

array([[[[[-0.421706  , -0.03188715,  1.47909315],
          [ 0.12155231,  0.02634163,  1.00504272],
          [ 0.92581232, -2.02998005,  1.62789541],
          [-1.7817046 ,  0.60441583,  0.92993722],
          [-0.62513521, -0.19782659,  1.72918574]],

         [[ 1.29670201, -0.28511315,  0.3227296 ],
          [-0.34538798, -0.90538621,  0.7104445 ],
          [-0.03476201, -1.33884198,  0.29361731],
          [-1.61326839, -1.30110148, -0.48380187],
          [ 0.98302063, -1.82972476,  0.55121492]]],


        [[[-0.67219335, -0.44480104, -1.32860569],
          [-0.75760033, -0.51114185, -1.2405695 ],
          [ 0.10523278, -0.66523584, -0.64939623],
          [ 3.06755962, -0.19341344,  1.34755542],
          [ 0.87023819,  0.64990568,  1.61116925]],

         [[ 0.56871813, -1.44355772, -0.00747844],
          [-0.95778766, -0.44961371,  0.19179691],
          [ 0.59210249, -1.07936357, -1.82369522],
          [ 0.20238236,  0.4819172 ,  0.5766533 ],
          [-0.810202  ,

In [118]:
np.random.randn(2,2,5,3)#(dim,dim,row,column)

array([[[[-0.47808494, -0.14490356, -0.39060419],
         [-1.64835018,  0.19112811,  0.46697757],
         [ 0.1353674 , -0.97299759,  1.30403641],
         [-0.32105697,  1.99476771, -0.90466308],
         [-1.28911999,  0.30191749,  0.49595167]],

        [[ 0.41262004,  0.36057674,  1.79553973],
         [-0.65191101,  0.34015922, -1.52637378],
         [ 0.55858949, -1.58911612, -2.09677938],
         [-0.26602289,  2.37433099, -1.18483813],
         [-0.25973178,  0.63055386,  1.34792334]]],


       [[[-1.34485478,  0.22649819,  1.04020323],
         [ 1.06004705,  0.75360531,  1.54609191],
         [-0.14526027,  0.40003059, -1.02020393],
         [ 0.36742979, -1.20545808, -1.30732839],
         [ 0.0180084 ,  0.04298641, -0.55933927]],

        [[ 0.3709901 ,  0.90446762,  1.96220862],
         [ 1.27868833, -0.23375884,  0.80066025],
         [-0.3958563 , -0.59283418,  2.03059931],
         [ 0.5187549 , -1.62457822, -0.1306164 ],
         [-1.14711878, -0.44430419,  0.241

In [119]:
np.random.randn(2,5,3)#(dim,row,column)

array([[[-0.75574463,  0.21474478, -1.9196894 ],
        [-1.39863956,  0.65173279,  0.54666466],
        [ 3.31057577,  0.31807514, -1.73863902],
        [ 0.80484029, -0.93083107,  0.60752277],
        [-0.08372331, -1.03219474, -1.98012607]],

       [[ 1.03890291,  0.55742297, -1.03220302],
        [-0.93297759,  1.63585885, -0.60294012],
        [-1.43757807,  0.09625277, -0.05192222],
        [ 0.07374943, -1.11903892, -0.89101078],
        [ 0.29361345,  0.81175412,  0.40891827]]])

In [120]:
np.random.randn(5,3)#(row,column)2 dimension

array([[-1.89315226e+00, -4.99128767e-01, -2.34019272e+00],
       [ 1.04744641e+00, -1.02870767e+00, -3.62736926e-01],
       [ 6.16147426e-01, -1.41843186e+00,  6.96516916e-01],
       [-1.67460242e+00, -1.48756990e+00,  6.46249714e-01],
       [ 9.22232440e-01,  1.31165805e-03, -8.22721083e-01]])

In [121]:
np.random.randn(3)#(column)1 dimension

array([-1.02930857,  1.04797776,  1.18243377])

In [125]:
x = np.random.randn(5,5)
x

array([[-1.19358887,  1.40104778,  0.12955404, -0.90234962,  0.6974798 ],
       [-0.36046903,  1.60630433,  0.76799423,  1.65225739, -2.07942425],
       [ 0.188336  ,  1.04306484, -0.54375495,  1.04912659, -2.06897423],
       [-2.19681206, -0.84511772,  0.24752499, -0.55916267, -1.96529773],
       [-0.16506864,  2.2054458 , -0.29757494, -1.56665275, -1.19384615]])

In [126]:
x[0]

array([-1.19358887,  1.40104778,  0.12955404, -0.90234962,  0.6974798 ])

In [128]:
x[4]

array([-0.16506864,  2.2054458 , -0.29757494, -1.56665275, -1.19384615])

In [132]:
x[4][4] #row with index 4 and in that index coulmn with index 4

-1.1938461494391015

In [133]:
x[4][0]

-0.16506863764466348

In [147]:
x[1:5:2,1:5:2]# [row index start:row index stop: step in slecting rows,column index start:column index stop: step in slecting columns]

array([[ 1.60630433,  1.65225739],
       [-0.84511772, -0.55916267]])

In [148]:
x[::,0:3]

array([[-1.19358887,  1.40104778,  0.12955404],
       [-0.36046903,  1.60630433,  0.76799423],
       [ 0.188336  ,  1.04306484, -0.54375495],
       [-2.19681206, -0.84511772,  0.24752499],
       [-0.16506864,  2.2054458 , -0.29757494]])

In [150]:
x[0:3,::]

array([[-1.19358887,  1.40104778,  0.12955404, -0.90234962,  0.6974798 ],
       [-0.36046903,  1.60630433,  0.76799423,  1.65225739, -2.07942425],
       [ 0.188336  ,  1.04306484, -0.54375495,  1.04912659, -2.06897423]])

In [151]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [153]:
x[1:-1,1:-1]= 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [154]:
x = np.ones((5,5))

In [166]:
x = np.ones((5,5))
x[0:5:2]=0
print(x)


[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [177]:
x = np.ones((5,5))
x[0:5:2,0:5:2]= 0
x[1:5:2,1:5:2]= 0
x

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

# functions

In [187]:
x = np.array([1,2,3,4,5])
print(x)
np.where(x<=3,0,x)# (condintion,value to placed, returned array as no else case)

[1 2 3 4 5]


array([0, 0, 0, 4, 5])

In [188]:
x = np.array([1,2,3,4,5])
print(x)
np.where(x<=3,"less than or equal to 3","greater than 3")# (condintion,value to placed, else case)

[1 2 3 4 5]


array(['less than or equal to 3', 'less than or equal to 3',
       'less than or equal to 3', 'greater than 3', 'greater than 3'],
      dtype='<U23')

In [2]:
import numpy as np

In [3]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(x)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [7]:
np.add(x,10)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.x+x

AttributeError: module 'numpy' has no attribute 'x'

In [10]:
y = x+x

In [11]:
y 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.maximum(x,y)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
x = np.array([1,5,6,2,3,4,7,0,8,9])

In [14]:
x.any()

True

In [16]:
x.mean()

4.5

In [17]:
x.max()

9

In [19]:
x.min()

0

In [20]:
x.cumprod()

array([   1,    5,   30,   60,  180,  720, 5040,    0,    0,    0],
      dtype=int32)

In [21]:
x.cumsum()

array([ 1,  6, 12, 14, 17, 21, 28, 28, 36, 45], dtype=int32)

In [22]:
y = x<5

In [23]:
y 

array([ True, False, False,  True,  True,  True, False,  True, False,
       False])

In [24]:
y.all()

False

In [25]:
y.any()

True

In [27]:
y.sum()

5

In [28]:
x.sort()
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# file input output

In [30]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,0])

In [31]:
np.save("abc",x)

In [3]:
x

NameError: name 'x' is not defined

In [34]:
loadx = np.load("abc.npy")

In [35]:
loadx

array([1, 2, 3, 4, 5])

In [42]:
np.save("abcy.npy" ,y)

In [43]:
loady = np.load("abcy.npy")

In [44]:
loady

array([6, 7, 8, 9, 0])

In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,0])

In [4]:
np.savez("abcxy.npy",x,y)

In [5]:
loadxy = np.load("abcxy.npy")

In [6]:
loadxy

array([1, 2, 3, 4, 5])

In [7]:
np.random.seed(8)

In [8]:
np.random.normal(size = (5,5))

array([[ 0.09120472,  1.09128273, -1.94697031, -1.38634953, -2.29649157],
       [ 2.4098343 ,  1.72783617,  2.20455628,  0.79482764,  0.9764211 ],
       [-1.18342715,  1.91636361, -1.1233268 , -0.66403547, -0.37835857],
       [-0.79161527,  0.85954811, -0.230789  , -0.06566103, -0.20863623],
       [ 1.34686857, -0.6069528 , -0.17424821,  0.42405142, -1.6459901 ]])

In [9]:
np.random.uniform(size = (3,3))

array([[0.80105589, 0.63823881, 0.06869013],
       [0.60364448, 0.79557456, 0.03200816],
       [0.45544782, 0.79017254, 0.98859652]])

#  Magic Methods / Function

In [ ]:
# magic methods

__init__
__add__
__len__
__repr__

In [1]:
# declare our own string class 
class String: 
	
	# magic method to initiate object 
	def __init__(self, string): 
		self.string = string 
		
	# print our string object 
	def __repr__(self): 
		return 'Object: {}'.format(self.string) 
		
	def __add__(self, other): 
		return self.string + other 

# Driver Code 
if __name__ == '__main__': 
	
	# object creation 
	string1 = String('Hello') 
	
	# concatenate String object and a string 
	print(string1 +' Geeks') 


Hello Geeks


In [2]:
dir(int) # Built-in classes in Python define many magic methods
# url :  https://www.tutorialsteacher.com/python/magic-methods-in-python

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

https://www.python-course.eu/python3_magic_methods.php

In [4]:
%history

# declare our own string class 
class String: 
    
    # magic method to initiate object 
    def __init__(self, string): 
        self.string = string 
        
    # print our string object 
    def __repr__(self): 
        return 'Object: {}'.format(self.string) 
        
    def __add__(self, other): 
        return self.string + other 

# Driver Code 
if __name__ == '__main__': 
    
    # object creation 
    string1 = String('Hello') 
    
    # concatenate String object and a string 
    print(string1 +' Geeks')
dir(int)
x
%history
