In [1]:
import numpy as np

In [3]:

#https://www.coursera.org/learn/neural-networks-deep-learning
a = np.random.randint(1,20,size = 20)
b = np.random.randint(1,10,size = 10)
print(a,b,sep= "\n\n")

[15 12 17  4 17  8  8 10  2  8  8 17  8 14 19  5 19 10  4 14]

[8 9 9 2 9 2 9 2 1 4]


In [5]:
np.in1d(a,b)

array([False, False, False,  True, False,  True,  True, False,  True,
        True,  True, False,  True, False, False, False, False, False,
        True, False])